modLoader="javafml"
loaderVersion="[44,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
	modId="apexcore"
	version="${file.jarVersion}"
	displayName="ApexCore"
	updateJSONURL="https://api.modrinth.com/updates/apexcore/forge_updates.json"
	displayURL="https://apexstudios.dev/apexcore"
	logoFile="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="Library Mod required by all of our Mods"
	displayTest="MATCH_VERSION"

[[dependencies.apexcore]]
	modId="forge"
	mandatory=true
	versionRange="[44.0.0,45.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		ignore=true
[[dependencies.apexcore]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.3,1.19.4)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		ignore=true
[[dependencies.apexcore]]
	modId="commonality"
	mandatory=true
	versionRange="[5.0.0,6.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		ignore=true
[[dependencies.apexcore]]
	modId="jei"
	mandatory=false
	versionRange="[12.0.0.0,)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		curseforge="jei"
