modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/ApexCore/issues"

[[mods]]
	modId="apexcore"
	version="${file.jarVersion}"
	displayName="ApexCore"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/apexcore.json"
	displayURL="https://apexstudios.dev/apexcore"
	logoFile="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="Library Mod required by all of our Mods"
	displayTest="MATCH_VERSION"

[[dependencies.apexcore]]
	modId="forge"
	mandatory=true
	versionRange="[43.1.1,44.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		ignore=true
[[dependencies.apexcore]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.2,1.20)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		ignore=true
[[dependencies.apexcore]]
	modId="commonality"
	mandatory=true
	versionRange="[4.1.0,5.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		ignore=true
[[dependencies.apexcore]]
	modId="jei"
	mandatory=false
	versionRange="[11.2.0.246,)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		curseforge="jei"