modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/ApexCore/issues"

[[mods]]
	modId="apexcore"
	version="${file.jarVersion}"
	displayName="ApexCore"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/apexcore.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/apexcore"
	logoFile="banner.png"
	credits="Apex - Programming"
	authors="Apex"
	description="Utility mod for all of Apex's mods."

[[dependencies.apexcore]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.60,41)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.apexcore]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.apexcore]]
	modId="jei"
	mandatory=false
	versionRange="[10.1.3.+,)"
	ordering="AFTER"
	side="BOTH"