modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/ApexCore/issues"

[[mods]]
	modId="apexcore"
	version="${file.jarVersion}"
	displayName="ApexCore"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/apexcore.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/apexcore"
	logoFile="banner.png"
	credits="Apex - Programming"
	authors="Apex"
	description="Utility mod for all of Apex's mods."
	displayTest="MATCH_VERSION"

[[dependencies.apexcore]]
	modId="forge"
	mandatory=true
	versionRange="[41,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.apexcore]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19,1.20)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.apexcore]]
	modId="jei"
	mandatory=false
	versionRange="[11.0.+,)"
	ordering="AFTER"
	side="BOTH"