modLoader="javafml"
loaderVersion="[36,)"
license="GNU"
issueTrackerURL="https://github.com/ApexModder/ApexCore/issues"

[[mods]]
modId="apexcore"
version="${file.jarVersion}"
displayName="ApexCore"
updateJSONURL="https://raw.githubusercontent.com/ApexModder/Version/master/apexcore.json"
# displayURL="https://www.curseforge.com/minecraft/mc-mods/apexcore"
# logoFile="logo.png"
credits="Apex - Programming"
authors="Apex"
description="Utility mod for all of Apex's mods."

[[dependencies.apexcore]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apexcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17]"
    ordering="NONE"
    side="BOTH"

[[dependencies.apexcore]]
    modId="registrator"
    mandatory=true
    versionRange="[1.0.16,2.0.0]"
    ordering="NONE"
    side="BOTH"