modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/ApexCore/issues"

[[mods]]
	modId="apexcore"
	version="${file.jarVersion}"
	displayName="ApexCore"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/apexcore.json"
	displayURL="https://apexstudios.dev/apexcore"
	logoFile="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="Library Mod required by all of our Mods"
	displayTest="MATCH_VERSION"

[[dependencies.apexcore]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.60,41)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		ignore=true
[[dependencies.apexcore]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		ignore=true
[[dependencies.apexcore]]
	modId="commonality"
	mandatory=true
	versionRange="[1.3.0,2.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		ignore=true
[[dependencies.apexcore]]
	modId="jei"
	mandatory=false
	versionRange="[9.7.1.+,)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.apexcore.custom.mc-publish]
		curseforge="jei"