modLoader="javafml"
loaderVersion="${forge_version_range}"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexModder/ApexCore/issues"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	updateJSONURL="https://raw.githubusercontent.com/ApexModder/Version/master/apexcore.json"
	# displayURL=""
	# logoFile=""
	credits="Apex - Programming"
	authors="${mod_authors}"
	description="Utility mod for all of Apex's mods."

[[dependencies.${mod_id}]]
	modId="forge"
	mandatory=true
	versionRange="${forge_version_range}"
	ordering="NONE"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="minecraft"
	mandatory=true
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
    modId="registrator"
    mandatory=true
    versionRange="${registrator_version_range}"
    ordering="NONE"
    side="BOTH"