modLoader="javafml"
loaderVersion="[${MCFORGE_LOADER_VERSION},)"
license="${MOD_LICENSE}"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
	modId="${MOD_ID}_testmod"
	version="${MOD_VERSION}"
	displayName="${MOD_NAME} - TestMod"
	updateJSONURL="https://api.modrinth.com/updates/apexcore/forge_updates.json"
	displayURL="https://apexstudios.dev/apexcore"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="TestMod for ${MOD_NAME}"
	displayTest="MATCH_VERSION"

[features."${MOD_ID}_testmod"]
	javaVersion="${JAVA_VERSION}"

[[dependencies."${MOD_ID}_testmod"]]
	modId="forge"
	mandatory=true
	versionRange="${MCFORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_testmod"]]
	modId="minecraft"
	mandatory=true
	versionRange="${MINECRAFT_FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_testmod"]]
	modId="${MOD_ID}"
	mandatory=true
	versionRange="[${MOD_VERSION},)"
	ordering="AFTER"
	side="BOTH"
